sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # install google cloud SDK
  - curl https://sdk.cloud.google.com | bash> /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  # Download and Install kubectl command line tool
  - gcloud components update kubectl
  # authorize google cloud sdk with service account
  - gcloud auth activate-servoce-account --key-file service-account.json
